version: '3.8'
services:
  artifacttoolkit-auth:
    build:
      context: ./artifacttoolkit-auth
      dockerfile: Dockerfile
    container_name: artifacttoolkit-auth
    ports:
      - "${SSH_PORT}:2222"
    volumes:
      - auth-opt:/opt

volumes:
  auth-opt:
