version: '3.8'

services:
  joplin-server:
    image: joplin/server
    ports:
      - "25001:22300"
    environment:
      - POSTGRES_PASSWORD=dummy_password
      - POSTGRES_USER=dummy_user
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx-start.sh:/nginx-start.sh # Add this line
    ports:
      - "25002:80"
      - "25003:443"
    depends_on:
      - joplin-server
    command: ["/nginx-start.sh"] # Update this line

  nfs-server:
    image: itsthenetwork/nfs-server-alpine
    volumes:
      - nfs-data:/nfsshare
    environment:
      - SHARED_DIRECTORY=/nfsshare
    ports:
      - "25004:2049"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=dummy_password
      - POSTGRES_USER=dummy_user
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  nfs-data:
    driver: local
  postgres-data:
    driver: local

