version: '3.8'
services:
  artifacttoolkit-auth:
    build: ./artifacttoolkit-auth
    container_name: artifacttoolkit-auth
    volumes:
      - ah-auth-opt:/opt

  artifacttoolkit-storage:
    build: ./artifacttoolkit-storage
    container_name: artifacttoolkit-storage
    ports:
      - "${NFS_PORT}:2049"
    volumes:
      - ah-storage-tools:${TOOLS_PATH}
      - ah-storage-artifacts:${ARTIFACTS_PATH}
      - ah-storage-git:${GIT_PATH}

volumes:
  ah-auth-opt:
  ah-storage-tools:
  ah-storage-artifacts:
  ah-storage-git:

