version: '3.8'
services:
  artifacttoolkit-auth:
    build:
      context: ./artifacttoolkit-auth
      dockerfile: Dockerfile
    container_name: artifacttoolkit-auth
    volumes:
      - ah-auth-opt:/opt

  artifacttoolkit-storage:
    build:
      context: ./artifacttoolkit-storage
      dockerfile: Dockerfile
    container_name: artifacttoolkit-storage
    privileged: true
    environment:
      - NFS_PORT=${NFS_PORT}
      - SMB_NETBIOS_PORT=${SMB_NETBIOS_PORT}
      - SMB_PORT=${SMB_PORT}
      - SMB_SECURE_PORT=${SMB_SECURE_PORT}
    ports:
      - "${NFS_PORT}:2049"
      - "${SMB_NETBIOS_PORT}:137"
      - "${SMB_PORT}:445"
      - "${SMB_SECURE_PORT}:5445"
    volumes:
      - ah-storage-tools:/opt/shares/tools
      - ah-storage-artifacts:/opt/shares/artifacts
      - ah-storage-git:/opt/shares/git

volumes:
  ah-auth-opt:
  ah-storage-tools:
  ah-storage-artifacts:
  ah-storage-git:

