version: '3.8'
services:
  artifacttoolkit-auth:
    build:
      context: ./artifacttoolkit-auth
      dockerfile: Dockerfile
    container_name: artifacttoolkit-auth
    volumes:
      - ah-auth-opt:/opt

  artifacttoolkit-storage:
    build:
      context: ./artifacttoolkit-storage
      dockerfile: Dockerfile
    container_name: artifacttoolkit-storage
    environment:
      - NFS_PORT=${NFS_PORT}
      - TOOLS_PATH=${TOOLS_PATH}
      - ARTIFACTS_PATH=${ARTIFACTS_PATH}
      - GIT_PATH=${GIT_PATH}
    ports:
      - "${NFS_PORT}:2049"
    volumes:
      - ah-storage-tools:${TOOLS_PATH}
      - ah-storage-artifacts:${ARTIFACTS_PATH}
      - ah-storage-git:${GIT_PATH}

volumes:
  ah-auth-opt:
  ah-storage-tools:
  ah-storage-artifacts:
  ah-storage-git:

