version: '3.8'
services:
  artifacttoolkit-auth:
    build:
      context: ./artifacttoolkit-auth
      dockerfile: Dockerfile
    container_name: atk-auth
    ports:
      - "${SSH_PORT}:2222"
    volumes:
      - auth-opt:/opt

  artifacttoolkit-nessus:
    build:
      context: ./artifacttoolkit-nessus
      dockerfile: Dockerfile
    container_name: atk-nessus
    ports:
      - "8834:8834"
    environment:
      - USERNAME=${NESSUS_USER}
      - PASSWORD=${NESSUS_PASSWORD}
    volumes:
      - nessus-data:/opt/nessus

volumes:
  auth-opt:
  nessus-data:
